class Equipo {
  String? id,
      idUser,
      numeroSerie,
      nas,
      fechaEntrega,
      hojaEntrega,
      notas,
      baja,
      detalleBaja,
      discoPrincipal,
      discoSecundario,
      estado,
      generacion,
      marca,
      modelo,
      operativa,
      procesador,
      ram,
      recepcion,
      sede,
      sistemaOperativo,
      tipo;

  Equipo({
    this.id,
    this.idUser,
    this.numeroSerie,
    this.nas,
    this.fechaEntrega,
    this.hojaEntrega,
    this.notas,
    this.baja,
    this.detalleBaja,
    this.discoPrincipal,
    this.discoSecundario,
    this.estado,
    this.generacion,
    this.marca,
    this.modelo,
    this.operativa,
    this.procesador,
    this.ram,
    this.recepcion,
    this.sede,
    this.sistemaOperativo,
    this.tipo,
  });

  factory Equipo.fromJson(Map<String, dynamic> json) {
    return Equipo(
      id: json['id'],
      numeroSerie: json['numero_serie'] ?? "",
      nas: json['nas'] ?? "",
      fechaEntrega: json['fecha_entrega'] ?? "",
      hojaEntrega: json['hoja_entrega'] ?? "",
      notas: json['notas'] ?? "",
      baja: json['baja'] ?? "",
      detalleBaja: json['detalle_baja'] ?? "",
      discoPrincipal: json['disco_principal'] ?? "",
      discoSecundario: json['disco_secundario'] ?? "",
      estado: json['estado'] ?? "",
      generacion: json['generacion'] ?? "",
      marca: json['marca'] ?? "",
      modelo: json['modelo'] ?? "",
      operativa: json['operativa'] ?? "",
      procesador: json['procesador'] ?? "",
      ram: json['ram'] ?? "",
      recepcion: json['recepcion'] ?? "",
      sede: json['sede'] ?? "",
      sistemaOperativo: json['sistema_operativo'] ?? "",
      tipo: json['tipo'] ?? "",
      idUser: json["id_user"]
    );
  }

  Map<String, dynamic> toJson() => {
    "id":id,
    "idUser":idUser,
    "numeroSerie":numeroSerie,
    "nas":nas,
    "fechaEntrega":fechaEntrega,
    "hojaEntrega":hojaEntrega,
    "notas":notas,
    "baja":baja,
    "detalleBaja":detalleBaja,
    "discoPrincipal":discoPrincipal,
    "discoSecundario":discoSecundario,
    "estado":estado,
    "generacion":generacion,
    "marca":marca,
    "modelo":modelo,
    "operativa":operativa,
    "procesador":procesador,
    "ram":ram,
    "recepcion":recepcion,
    "sede":sede,
    "sistemaOperativo":sistemaOperativo,
    "tipo":tipo,
  };
}
